### ISSUE TITLE
premake 5.0.0-beta1 doesn't understand `externalwarnings`, `externalincludedirs` tags

### ISSUE THREAD

**Issue by jgusta** [Unbundlesss/OUROVEON#6]
The bundled macos version of premake that `premake-osx.sh` uses (`5.0.0-beta1`) doesn't recognize a few configuration tags. However I confirm premake 5.0.0-beta2 works. This is also the current version installed by homebrew.

**Comment by ishani** [comment]
Ah yeah, I'll need to update when I flip back to getting Mac builds going again, good shout. I've been rattling through changes on PC at the moment, current latest might be a bit in-flux for a bit

(I can post notarised MacOS builds from a few weeks back if that's useful)

**Comment by ishani** [comment]
[20230425-232343.LORE.0.7.1.zip](https://github.com/Unbundlesss/OUROVEON/files/11768693/20230425-232343.LORE.0.7.1.zip)

Here's a 0.7.1 build in case its useful. I'll get some 0.7.4 builds rolling out soon. Also need to do some new docs!

**Comment by ishani** [comment]
0.7.5 posted to jamsss, also attached. code at time of writing should build on MacOS again, premake updated to beta 2 and the usual mess of things fixed
[MacOS-LORE-0.7.5-alpha-20230704.zip](https://github.com/Unbundlesss/OUROVEON/files/11952477/MacOS-LORE-0.7.5-alpha-20230704.zip)
